import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Home from "../src/components/home";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />

      {/* <footer className={styles.footer}></footer> */}
    </>
  );
}
